### ISSUE TITLE
NullReferenceException in Parse.Internal.HttpClient

### ISSUE THREAD

**Issue by kostub** [ParsePlatform/Parse-SDK-dotNET#106]
Every so often while making Parse queries we get this exception in `Parse.Internal.HttpClient`. It seems happen usually for the queries that we make as soon as the app starts up, but I've seen it happen in other places as well.

Looking at the disassembly, this seems to happen somewhere between lines 100-130 in HttpClient.iOS.cs, but I don't have exact line numbers so I can't say that for sure. I didn't see anything obvious that would be `null` there though.

```
System.NullReferenceExceptionObject reference not set to an instance of an object
  at Parse.Internal.HttpClient+<>c__DisplayClass15.<ExecuteAsync>b__d (System.Threading.Tasks.Task`1 t) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[TAntecedentResult,TResult].InnerInvoke () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[TResult].<OnSuccess>b__6 (System.Threading.Tasks.Task t) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[TResult].<OnSuccess>b__6 (System.Threading.Tasks.Task t) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[TResult].<OnSuccess>b__6 (System.Threading.Tasks.Task t) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0 
  at Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[TResult].<OnSuccess>b__6 (System.Threading.Tasks.Task t) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00000] in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <filename unknown>:0 
  at MathChat.Exceptions.ServerException+<Wrap>c__async1`1[System.Collections.Generic.IEnumerable`1[MathChat.Models.Parse.PUser]].MoveNext () [0x00000] in <filename unknown>:0 
```

**Comment by richardjrossiii** [comment]
Hmm. That certainly is strange. My initial thoughts are  that it may be from `resultStream` being null due to a transient connection issue? We've seen similar things on the other platforms.

I'm going to mark this as needs more info until we can find a more consistent reproduction case.

I'd suggest building the SDK yourself and seeing if you can cause it to fail with debug symbols available.

**Comment by kostub** [comment]
Not able to reproduce this with 1.6.2 so I assume it has been fixed. I will confirm when our app with that release goes into production.

**Comment by bwail** [comment]
It seems the issue is still there, confirmed on version 1.7.0
Parse.Android


<pre>
  at Parse.Internal.HttpClient+<>c__DisplayClass15.<ExecuteAsync>b__d (System.Threading.Tasks.Task`1 t) [0x00093] in <filename unknown>:0 
  at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[TAntecedentResult,TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:207 
  at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2523 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[TResult].<OnSuccess>b__6 (System.Threading.Tasks.Task t) [0x00033] in <filename unknown>:0 
  at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:111 
  at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2523 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[TResult].<OnSuccess>b__6 (System.Threading.Tasks.Task t) [0x00033] in <filename unknown>:0 
  at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:111 
  at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2523 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:201 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:170 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:142 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:124 
  at FutureMed.Core.InitServer+<TestServer>d__1.MoveNext () [0x0004f]
</pre>

**Comment by rehos** [comment]
I can also confirm that this issue is still there (I'am having the same stack trace as @bwail). The issue can be reproduced if you have no internet connection.

**Comment by rehos** [comment]
This bug is probably fixed in commit 7fb6a9ad6. I cannot confirm this because I'am not able to build this project on my Mac due to issue #191.

**Comment by rehos** [comment]
The different implementations for HttpClient contain the following code in version 1.7.0 of the SDK:
```
        var resultStream = new MemoryStream();
        HttpWebResponse response = null;
        if (t.IsFaulted) {
          if (t.Exception.InnerException is WebException) {
            var webException = t.Exception.InnerException as WebException;
            response = (HttpWebResponse)webException.Response;
          } else {
            TaskCompletionSource<Tuple<HttpStatusCode, string>> tcs = new TaskCompletionSource<Tuple<HttpStatusCode, string>>();
            tcs.TrySetException(t.Exception);

            return tcs.Task;
          }
        } else {
          response = (HttpWebResponse)t.Result;
        }

        var responseStream = response.GetResponseStream();
        int bufferSize = 4096;
        byte[] buffer = new byte[bufferSize];
        int bytesRead = 0;
        long totalLength = -1;
        long readSoFar = 0;
```

The problem is that the following line can set *response* to *null* (i.e. if there is no network and you get a NameResolutionFailure):
```
response = (HttpWebResponse)webException.Response
```
Because *response* is null under these circumstances the following line raises a null reference exception:
```
var responseStream = response.GetResponseStream();
```

**Comment by rehos** [comment]
For anyone interested, this is my fix bd121f68db56641a49608685a5bb001001a054c1
