### ISSUE TITLE
Parse.ParseException: Invalid response from server

### ISSUE THREAD

**Issue by brilvio** [ParsePlatform/Parse-SDK-dotNET#203]
I trying to do my own parse server with node.js but I don't think that the app is connecting with the server.

I am doing the app with Xamarin and the Parse.android.dll  1.7.0.

Here is the ParseApplication.cs
```c#
using System;
using Android.App;
using Android.Runtime;
using Parse;

namespace App7
{
    [Application(Name = "app7.ParseApplication")]
    class ParseApplication : Application
    {
        public ParseApplication(IntPtr handle, JniHandleOwnership ownerShip)
          : base(handle, ownerShip)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();

            ParseClient.Initialize(new ParseClient.Configuration
            {
                ApplicationId = "appid",
                Server = "http://10.0.0.100:1337/parse"
            });
    
            ParsePush.ParsePushNotificationReceived += ParsePush.DefaultParsePushNotificationReceivedHandler;


        }
    }
}
```

Here is the code that is causing the error:

```c#
 private async void Button_Click(object sender, EventArgs e)
        {           
            ParseObject gameScore = new ParseObject("GameScore");
            gameScore["score"] = 1111;
            gameScore["playerName"] = "test";
            await gameScore.SaveAsync();
        } 
```

When tring a get the instalations 10.0.0.100:1337/parse/installations returns a empty result.

I have configured the manifest like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.fernando" android:versionCode="1" android:versionName="1.0" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="21" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.WAKE_LOCK" />
	<uses-permission android:name="android.permission.VIBRATE" />
	<uses-permission android:name="android.permission.GET_ACCOUNTS" />
	<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
	<permission android:protectionLevel="signature" android:name="com.fernando.permission.C2D_MESSAGE" />
	<application android:name="app7.ParseApplication" android:label="App7">
		<receiver android:name="parse.ParsePushBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
			<intent-filter>
				<action android:name="com.google.android.c2dm.intent.RECEIVE" />
				<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
				<category android:name="com.fernando" />
			</intent-filter>
		</receiver>
		<service android:name="parse.ParsePushService" />
		<meta-data android:name="com.parse.push.gcm_sender_id" android:value="id:SENDERID" />
	</application>
</manifest>
```

The log of the error when I click the button:

```
Unhandled Exception:

Parse.ParseException: Invalid response from server

Thread finished: <Thread Pool> #5
04-17 17:47:57.290 D/Mono    ( 1326): [0xb9765108] worker finishing
04-17 17:47:57.922 D/Mono    ( 1326): DllImport attempting to load: '/system/lib/liblog.so'.
04-17 17:47:57.922 D/Mono    ( 1326): DllImport loaded library '/system/lib/liblog.so'.
04-17 17:47:57.922 D/Mono    ( 1326): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
04-17 17:47:57.922 D/Mono    ( 1326): Searching for '__android_log_print'.
04-17 17:47:57.922 D/Mono    ( 1326): Probing '__android_log_print'.
04-17 17:47:57.922 I/MonoDroid( 1326): UNHANDLED EXCEPTION:
04-17 17:47:57.922 I/MonoDroid( 1326): Parse.ParseException: Invalid response from server ---> System.ArgumentException: Input JSON was invalid.
04-17 17:47:57.922 I/MonoDroid( 1326):   at Parse.Internal.Json.Parse (System.String input) [0x00033] in <filename unknown>:0 
04-17 17:47:57.922 I/MonoDroid( 1326):   at Parse.Internal.ParseCommandRunner+<>c__DisplayClass2.<RunCommandAsync>b__1 (System.Threading.Tasks.Task`1 t) [0x0006d] in <filename unknown>:0 
04-17 17:47:57.922 I/MonoDroid( 1326):   --- End of inner exception stack trace ---
04-17 17:47:57.922 I/MonoDroid( 1326):   at Parse.Internal.ParseCommandRunner+<>c__DisplayClass2.<RunCommandAsync>b__1 (System.Threading.Tasks.Task`1 t) [0x0008a] in <filename unknown>:0 
04-17 17:47:57.922 I/MonoDroid( 1326):   at Parse.Internal.InternalExtensions+<>c__DisplayClass1`2[TIn,TResult].<OnSuccess>b__0 (System.Threading.Tasks.Task t) [0x00000] in <filename unknown>:0 
04-17 17:47:57.922 I/MonoDroid( 1326):   at Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[TResult].<OnSuccess>b__6 (System.Threading.Tasks.Task t) [0x0006f] in <filename unknown>:0 
04-17 17:47:57.922 I/MonoDroid( 1326):   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:111 
04-17 17:47:57.922 I/MonoDroid( 1326):   at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2523 
04-17 17:47:57.922 I/MonoDroid( 1326): --- End of stack trace from previous location where exception was thrown ---
04-17 17:47:57.922 I/MonoDroid( 1326):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
04-17 17:47:57.922 I/MonoDroid( 1326):   at Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[TResult].<OnSuccess>b__6 (System.Threading.Tasks.Task t) [0x00033] in <filename unknown>:0 
04-17 17:47:57.922 I/MonoDroid( 1326):   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:111 
04-17 17:47:57.922 I/MonoDroid( 1326):   at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2523 
04-17 17:47:57.922 I/MonoDroid( 1326): --- End of stack trace from previous location where exception was thrown ---
04-17 17:47:57.922 I/MonoDroid( 1326):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
04-17 17:47:57.922 I/MonoDroid( 1326):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:201 
04-17 17:47:57.922 I/MonoDroid( 1326):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:170 
04-17 17:47:57.922 I/MonoDroid( 1326):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:142 
04-17 17:47:57.922 I/MonoDroid( 1326):   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:124 
04-17 17:47:57.922 I/MonoDroid( 1326):   at App7.MainActivity+<Button_Click>d__2.MoveNext () [0x0006f] in C:\Users\ferna\Documents\Visual Studio 2015\Projects\App7\App7\MainActivity.cs:38 
04-17 17:47:57.922 I/MonoDroid( 1326): --- End of stack trace from previous location where exception was thrown ---
04-17 17:47:57.922 I/MonoDroid( 1326):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
04-17 17:47:57.922 I/MonoDroid( 1326):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:994 
04-17 17:47:57.922 I/MonoDroid( 1326):   at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:18 
04-17 17:47:57.922 I/MonoDroid( 1326):   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36 
04-17 17:47:57.922 I/MonoDroid( 1326):   at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3053/a94a03b5/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Java.Lang.IRunnable.cs:71 
04-17 17:47:57.922 I/MonoDroid( 1326):   at (wrapper dynamic-method) System.Object:9a8e2787-33b2-4748-87e9-be1d1a569ce1 (intptr,intptr)
04-17 17:47:57.922 D/Mono    ( 1326): Found as '__android_log_print'.
The thread '<Thread Pool>' (0x5) has exited with code 0 (0x0).
An unhandled exception occured.

In mgmain JNI_OnLoad
04-17 17:47:58.566 E/mono    ( 1326): 
04-17 17:47:58.566 E/mono    ( 1326): Unhandled Exception:
04-17 17:47:58.566 E/mono    ( 1326): Parse.ParseException: Invalid response from server ---> System.ArgumentException: Input JSON was invalid.
04-17 17:47:58.566 E/mono    ( 1326):   at Parse.Internal.Json.Parse (System.String input) [0x00033] in <filename unknown>:0 
04-17 17:47:58.566 E/mono    ( 1326):   at Parse.Internal.ParseCommandRunner+<>c__DisplayClass2.<RunCommandAsync>b__1 (System.Threading.Tasks.Task`1 t) [0x0006d] in <filename unknown>:0 
04-17 17:47:58.566 E/mono    ( 1326):   --- End of inner exception stack trace ---
04-17 17:47:58.566 E/mono    ( 1326):   at Parse.Internal.ParseCommandRunner+<>c__DisplayClass2.<RunCommandAsync>b__1 (System.Threading.Tasks.Task`1 t) [0x0008a] in <filename unknown>:0 
04-17 17:47:58.566 E/mono    ( 1326):   at Parse.Internal.InternalExtensions+<>c__DisplayClass1`2[TIn,TResult].<OnSuccess>b__0 (System.Threading.Tasks.Task t) [0x00000] in <filename unknown>:0 
04-17 17:47:58.566 E/mono    ( 1326):   at Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[TResult].<OnSuccess>b__6 (System.Threading.Tasks.Task t) [0x0006f] in <filename unknown>:0 
04-17 17:47:58.566 E/mono    ( 1326):   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:111 
04-17 17:47:58.566 E/mono    ( 1326):   at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2523 
04-17 17:47:58.566 E/mono    ( 1326): --- End of stack trace from previous location where exception was thrown ---
04-17 17:47:58.566 E/mono    ( 1326):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
04-17 17:47:58.566 E/mono    ( 1326):   at Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[TResult].<OnSuccess>b__6 (System.Threading.Tasks.Task t) [0x00033] in <filename unknown>:0 
04-17 17:47:58.566 E/mono    ( 1326):   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:111 
04-17 17:47:58.566 E/mono    ( 1326):   at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2523 
04-17 17:47:58.566 E/mono    ( 1326): --- End of stack trace from previous location where exception was thrown ---
04-17 17:47:58.566 E/mono    ( 1326):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
04-17 17:47:58.566 E/mono    ( 1326):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:201 
04-17 17:47:58.566 E/mono    ( 1326):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:170 
04-17 17:47:58.566 E/mono    ( 1326):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:142 
04-17 17:47:58.566 E/mono    ( 1326):   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:124 
04-17 17:47:58.566 E/mono    ( 1326):   at App7.MainActivity+<Button_Click>d__2.MoveNext () [0x0006f] in C:\Users\ferna\Documents\Visual Studio 2015\Projects\App7\App7\MainActivity.cs:38 
04-17 17:47:58.566 E/mono    ( 1326): --- End of stack trace from previous location where exception was thrown ---
04-17 17:47:58.566 E/mono    ( 1326):   at (wrapper dynamic-method) System.Object:9a8e2787-33b2-4748-87e9-be1d1a569ce1 (intptr,intptr)
04-17 17:47:58.566 E/mono    ( 1326):   at (wrapper native-to-managed) System.Object:9a8e2787-33b2-4748-87e9-be1d1a569ce1 (intptr,intptr)
04-17 17:47:58.566 E/mono-rt ( 1326): [ERROR] FATAL UNHANDLED EXCEPTION: Parse.ParseException: Invalid response from server ---> System.ArgumentException: Input JSON was invalid.
04-17 17:47:58.566 E/mono-rt ( 1326):   at Parse.Internal.Json.Parse (System.String input) [0x00033] in <filename unknown>:0 
04-17 17:47:58.566 E/mono-rt ( 1326):   at Parse.Internal.ParseCommandRunner+<>c__DisplayClass2.<RunCommandAsync>b__1 (System.Threading.Tasks.Task`1 t) [0x0006d] in <filename unknown>:0 
04-17 17:47:58.566 E/mono-rt ( 1326):   --- End of inner exception stack trace ---
04-17 17:47:58.566 E/mono-rt ( 1326):   at Parse.Internal.ParseCommandRunner+<>c__DisplayClass2.<RunCommandAsync>b__1 (System.Threading.Tasks.Task`1 t) [0x0008a] in <filename unknown>:0 
04-17 17:47:58.566 E/mono-rt ( 1326):   at Parse.Internal.InternalExtensions+<>c__DisplayClass1`2[TIn,TResult].<OnSuccess>b__0 (System.Threading.Tasks.Task t) [0x00000] in <filename unknown>:0 
04-17 17:47:58.566 E/mono-rt ( 1326):   at Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[TResult].<OnSuccess>b__6 (System.Threading.Tasks.Task t) [0x0006f] in <filename unknown>:0 
04-17 17:47:58.566 E/mono-rt ( 1326):   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:111 
04-17 17:47:58.566 E/mono-rt ( 1326):   at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2523 
04-17 17:47:58.566 E/mono-rt ( 1326): --- End of stack trace from previous location where exception was thrown ---
04-17 17:47:58.566 E/mono-rt ( 1326):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
04-17 17:47:58.566 E/mono-rt ( 1326):   at Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[TResult].<OnSuccess>b__6 (System.Threading.Tasks.Task t) [0x00033] in <filename unknown>:0 
04-17 17:47:58.566 E/mono-rt ( 1326):   at System.Threading.Tasks.ContinuationResultTaskFromTask`1[TResult].InnerInvoke () [0x00027] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/TaskContinuation.cs:111 
04-17 17:47:58.566 E/mono-rt ( 1326):   at System.Threading.Tasks.Task.Execute () [0x00016] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/threading/Tasks/Task.cs:2523 
04-17 17:47:58.566 E/mono-rt ( 1326): --- End of stack trace from previous location where exception was thrown ---
04-17 17:47:58.566 E/mono-rt ( 1326):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
04-17 17:47:58.566 E/mono-rt ( 1326):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:201 
04-17 17:47:58.566 E/mono-rt ( 1326):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:170 
04-17 17:47:58.566 E/mono-rt ( 1326):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:142 
04-17 17:47:58.566 E/mono-rt ( 1326):   at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/3053/a94a03b5/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:124 
04-17 17:47:58.566 E/mono-rt ( 1326):   at App7.MainActivity+<Button_Click>d__2.MoveNext () [0x0006f] in C:\Users\ferna\Documents\Visual Studio 2015\Projects\App7\App7\MainActivity.cs:38 
04-17 17:47:58.566 E/mono-rt ( 1326): --- End of stack trace from previous location where exception was thrown ---
04-17 17:47:58.566 E/mono-rt ( 1326):   at (wrapper dynamic-method) System.Object:9a8e2787-33b2-4748-87e9-be1d1a569ce1 (intptr,intptr)
04-17 17:47:58.566 E/mono-rt ( 1326):   at (wrapper native-to-managed) System.Object:9a8e2787-33b2-4748-87e9-be1d1a569ce1 (intptr,intptr)
```

**Comment by zeroexu** [comment]
I also have this error. I am following this thread.

**Comment by richardjrossiii** [comment]
Can you validate that connecting to the server works via CURL? Or one of our other SDKs? (Perhaps it's mounted on a different URL path than /parse?)

**Comment by brilvio** [comment]
@richardjrossiii Yes I can get to work with curl, I try to use the curl for getting the installations it works fine but the result is empty I will try with another SDK, with the built in one in /test works fine, but I will do a test with a html/js to see if it works. I tried with the latest SDK on nuget, and I did the steps in the docs as you can see in my ParseApplication.cs and im my android manifest.

**Comment by richardjrossiii** [comment]
@brilvio can you try adding a `/` after your path? IIRC, the latest release of the .NET SDK requires path construction to end with a '/' (this has been fixed on master).

**Comment by brilvio** [comment]
I will try, in meanwhile I tested with the javascript sdk and works fine I can send the object to the server.

**Comment by brilvio** [comment]
@richardjrossiii Now I can send the objects it was the `/` after all, but I still get the installations empty.
I don't know if I have to open another issue.

**Comment by richardjrossiii** [comment]
Yes, please open another issue with as much information you can. We've gotten another report a few days ago of installations missing 'deviceToken', which might be related.

**Comment by NadjibR** [comment]
> @brilvio can you try adding a `/` after your path? IIRC, the latest release of the .NET SDK requires path construction to end with a '/' (this has been fixed on master).

I had the same error exception. And I confirm that by adding a `/` to my path (http://server/parse/), my application works fine now. Thank you :)
